[package]
name = "leafs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geo = "0.24.0"
geo-svg = "0.5.0"
nannou = "0.18.1"
rand = "0.8.5"
